//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace YS_scrtaskboard.Entities
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    using System.Data.Entity.Core.Objects;
    using System.Linq;
    
    public partial class YSprojeEntities : DbContext
    {
        public YSprojeEntities()
            : base("name=YSprojeEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<tblDurumlar> tblDurumlar { get; set; }
        public virtual DbSet<tblGorevDurum> tblGorevDurum { get; set; }
        public virtual DbSet<tblGorevler> tblGorevler { get; set; }
        public virtual DbSet<tblKisiler> tblKisiler { get; set; }
        public virtual DbSet<tblKullanicilar> tblKullanicilar { get; set; }
        public virtual DbSet<tblProjeler> tblProjeler { get; set; }
        public virtual DbSet<view_GorevDurumDetay> view_GorevDurumDetay { get; set; }
        public virtual DbSet<view_Genel> view_Genel { get; set; }
        public virtual DbSet<vw_Check> vw_Check { get; set; }
        public virtual DbSet<vw_Done> vw_Done { get; set; }
        public virtual DbSet<vw_inProgress> vw_inProgress { get; set; }
        public virtual DbSet<vw_Revision> vw_Revision { get; set; }
        public virtual DbSet<vw_Todo> vw_Todo { get; set; }
    
        [DbFunction("YSprojeEntities", "f_TeknikKartDetay")]
        public virtual IQueryable<f_TeknikKartDetay_Result> f_TeknikKartDetay(Nullable<int> projeNo)
        {
            var projeNoParameter = projeNo.HasValue ?
                new ObjectParameter("ProjeNo", projeNo) :
                new ObjectParameter("ProjeNo", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.CreateQuery<f_TeknikKartDetay_Result>("[YSprojeEntities].[f_TeknikKartDetay](@ProjeNo)", projeNoParameter);
        }
    
        public virtual int sp_GorevEkle(Nullable<int> projID, Nullable<int> kisiID, Nullable<System.DateTime> kartTarih, Nullable<System.DateTime> tahmin, Nullable<System.DateTime> gercekBitis, string gorevAd, string gorevAciklama, string gorevNotlar, ObjectParameter kartNo)
        {
            var projIDParameter = projID.HasValue ?
                new ObjectParameter("ProjID", projID) :
                new ObjectParameter("ProjID", typeof(int));
    
            var kisiIDParameter = kisiID.HasValue ?
                new ObjectParameter("KisiID", kisiID) :
                new ObjectParameter("KisiID", typeof(int));
    
            var kartTarihParameter = kartTarih.HasValue ?
                new ObjectParameter("KartTarih", kartTarih) :
                new ObjectParameter("KartTarih", typeof(System.DateTime));
    
            var tahminParameter = tahmin.HasValue ?
                new ObjectParameter("Tahmin", tahmin) :
                new ObjectParameter("Tahmin", typeof(System.DateTime));
    
            var gercekBitisParameter = gercekBitis.HasValue ?
                new ObjectParameter("GercekBitis", gercekBitis) :
                new ObjectParameter("GercekBitis", typeof(System.DateTime));
    
            var gorevAdParameter = gorevAd != null ?
                new ObjectParameter("GorevAd", gorevAd) :
                new ObjectParameter("GorevAd", typeof(string));
    
            var gorevAciklamaParameter = gorevAciklama != null ?
                new ObjectParameter("GorevAciklama", gorevAciklama) :
                new ObjectParameter("GorevAciklama", typeof(string));
    
            var gorevNotlarParameter = gorevNotlar != null ?
                new ObjectParameter("GorevNotlar", gorevNotlar) :
                new ObjectParameter("GorevNotlar", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("sp_GorevEkle", projIDParameter, kisiIDParameter, kartTarihParameter, tahminParameter, gercekBitisParameter, gorevAdParameter, gorevAciklamaParameter, gorevNotlarParameter, kartNo);
        }
    }
}
