//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace YS_scrtaskboard.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblGorevDurum
    {
        public int GorevDurumID { get; set; }
        public int KisiID { get; set; }
        public int ProjeID { get; set; }
        public int GorevID { get; set; }
        public int DurumID { get; set; }
        public string GorevDurumAciklama { get; set; }
        public Nullable<System.DateTime> GorevDurumTarih { get; set; }
    
        public virtual tblDurumlar tblDurumlar { get; set; }
        public virtual tblGorevler tblGorevler { get; set; }
        public virtual tblKisiler tblKisiler { get; set; }
        public virtual tblProjeler tblProjeler { get; set; }
    }
}
