//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace YS_scrtaskboard.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblGorevler
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public tblGorevler()
        {
            this.tblGorevDurum = new HashSet<tblGorevDurum>();
        }
    
        public int GorevID { get; set; }
        public string GorevAd { get; set; }
        public string GorevAciklama { get; set; }
        public string GorevNotlar { get; set; }
        public Nullable<System.DateTime> GorevTarihi { get; set; }
        public Nullable<System.DateTime> GorevTahBitis { get; set; }
        public Nullable<System.DateTime> GorevBitisTar { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tblGorevDurum> tblGorevDurum { get; set; }
    }
}
