//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace YS_scrtaskboard.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblKullanicilar
    {
        public int KulID { get; set; }
        public int KisiID { get; set; }
        public string KulAd { get; set; }
        public string Parola { get; set; }
    
        public virtual tblKisiler tblKisiler { get; set; }
    }
}
